name: Build and Push OCI Images

on:
  push:
    branches: ["main"]
  workflow_dispatch:

env:
  REGISTRY: ghcr.io

jobs:
  build-rocm-and-cpu:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Lowercase repository name
        run: echo "REPO_LOWER=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Build and push openai-whsiper:rocm image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: SOPs/openai-whisper/Dockerfile.openai-whsiper:rocm
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.REPO_LOWER }}/openai-whisper:rocm
            ${{ env.REGISTRY }}/${{ env.REPO_LOWER }}/openai-whisper:rocm-latest
          cache-from: type=gha # 用GitHub Actions缓存加速后续构建
          cache-to: type=gha,mode=max
          platforms: linux/amd64

      - name: Build and push openai-whsiper:rocm image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: SOPs/openai-whisper/Dockerfile.openai-whsiper:cpu
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.REPO_LOWER }}/openai-whisper:cpu
            ${{ env.REGISTRY }}/${{ env.REPO_LOWER }}/openai-whisper:cpu-latest
          cache-from: type=gha # 用GitHub Actions缓存加速后续构建
          cache-to: type=gha,mode=max
          platforms: linux/amd64,linux/arm64
